"""
Builds a human-readable markdown report from the classification +
Claude analysis. Same formatter is reused regardless of platform —
only the sink (where it gets posted) differs.
"""

from pipefix.detection.classifier import ClassificationResult

SEVERITY_EMOJI = {
    "LOW": "🟢",
    "MEDIUM": "🟡",
    "HIGH": "🟠",
    "CRITICAL": "🔴",
}

CONFIDENCE_EMOJI = {
    "low": "❓",
    "medium": "✅",
    "high": "✅",
}


def format_report(classification: ClassificationResult, analysis: dict, commit_sha: str = "") -> str:
    severity = analysis.get("severity", "MEDIUM")
    confidence = analysis.get("confidence", "medium")

    sev_icon = SEVERITY_EMOJI.get(severity, "🟡")
    conf_icon = CONFIDENCE_EMOJI.get(confidence, "✅")

    lines = []
    lines.append("## 🩺 Pipefix — Failure Analysis\n")

    meta_bits = []
    if commit_sha:
        meta_bits.append(f"Commit: `{commit_sha[:8]}`")
    meta_bits.append(f"Severity: {sev_icon} {severity}")
    meta_bits.append(f"Confidence: {conf_icon} {confidence}")
    if analysis.get("cached"):
        meta_bits.append("💾 Cached result (no API call)")
    lines.append(" | ".join(meta_bits) + "\n")

    if classification.stages:
        stage_badges = " ".join(f"`{s}`" for s in classification.stages)
        lines.append(f"**Stages affected:** {stage_badges}")
    if classification.languages:
        lang_badges = " ".join(f"`{l}`" for l in classification.languages)
        lines.append(f"**Languages detected:** {lang_badges}")
    lines.append("")

    lines.append("### 🔍 Root Cause")
    lines.append(analysis.get("root_cause", "No root cause determined.") + "\n")

    fixes = analysis.get("fixes", [])
    if fixes:
        lines.append("### 🛠️ Suggested Fixes")
        for i, fix in enumerate(fixes, 1):
            lines.append(f"**Fix {i}: {fix.get('title', 'Suggested change')}**")
            lines.append(fix.get("explanation", ""))
            code = fix.get("code", "")
            if code:
                lines.append(f"```\n{code}\n```")
            lines.append("")

    prevention = analysis.get("prevention", "")
    if prevention:
        lines.append("### 🛡️ Prevention")
        lines.append(prevention + "\n")

    lines.append("---")
    lines.append("_Generated by Pipefix — works across GitHub Actions and GitLab CI._")

    return "\n".join(lines)
